baseurl = "https://blog.pierrickdeniel.fr/"
# remember trailing / at end of baseurl
languageCode = "fr-fr"
title = "HELLO GOOGLE 💖"
# Enable comments by entering your Disqus shortname
# disqusShortname = ""
# Enable Google Analytics by entering your tracking code
# googleAnalytics = ""
paginate = 50
theme = "hugo"

[permalinks]
	post = "/:year/:month/:day/:slug"

[params]
	name = "Pierrick Deniel"
	description = "ส้้้้้้้้้้้้้้้้้้้้้้้้ส้้้้้้้้้้้้้้้้้้้้้้้้ Ꙭ HELLO GOOGLE Ꙭ ONLY CRAPPY SEO TEST HERE Ꙭ ส้้้้้้้้้้้้้้้้้้้้้้้้ส้้้้้้้้้้้้้้้้้้้้้้้้"
	copyright = ""

	# Custom assets can be linked with their paths relative to static/
	custom_css = []
	custom_js  = []

	# Links to newer/older blog posts
	newer = "nwr"
	older = "oldr"

	pageNotFoundTitle = "Page non trouvée"
	pageNotFoundSubtitle = "Toi t'es <br>perdu."

[params.offcanvas]
	# Menu items
	title = "62 4b 4e"
	bio = "44°50.4264′ - 0°34.83′"
	bio2 = "01100010 01101111 01110010 01100100 01100101 01100001 01110101 01111000"
	subscribe = "S'abonner"
	followme = "Contact"

	# Enable Google search
	search_enabled = false
	search = "Search"

	[[params.offcanvas.socialnetworks]]
		name = "twitter"
		url = "https://twitter.com/bKN____"
